[build noble] fix ci

diff --git a/noble/Dockerfile b/noble/Dockerfile
--- a/noble/Dockerfile
+++ b/noble/Dockerfile
@@ -2,6 +2,9 @@ FROM ros:jazzy-perception-noble
 
 ARG USER_ID
 
+# check args not empty
+RUN if [ -z "$USER_ID" ]; then echo "USER_ID argument is required"; exit 1; fi
+
 # delete ubuntu user
 RUN sudo userdel ubuntu
 
diff --git a/noble/Dockerfile-robot b/noble/Dockerfile-robot
--- a/noble/Dockerfile-robot
+++ b/noble/Dockerfile-robot
@@ -7,6 +7,11 @@ ARG RECIPES_TAG
 ARG FOREST_NJOBS=1
 ARG USER_ID
 
+# check args not empty
+RUN if [ -z "$USER_ID" ]; then echo "USER_ID argument is required"; exit 1; fi
+RUN if [ -z "$RECIPES_REPO" ]; then echo "RECIPES_REPO argument is required"; exit 1; fi
+RUN if [ -z "$RECIPES_TAG" ]; then echo "RECIPES_TAG argument is required"; exit 1; fi
+
 ## persistent env variables
 ENV HHCM_FOREST_CLONE_DEFAULT_PROTO=https
 
diff --git a/noble/Dockerfile-rt b/noble/Dockerfile-rt
--- a/noble/Dockerfile-rt
+++ b/noble/Dockerfile-rt
@@ -7,6 +7,12 @@ ARG FOREST_NJOBS=1
 ARG KERNEL_VER
 ARG USER_ID
 
+# check args not empty
+RUN if [ -z "$USER_ID" ]; then echo "USER_ID argument is required"; exit 1; fi
+RUN if [ -z "$RECIPES_REPO" ]; then echo "RECIPES_REPO argument is required"; exit 1; fi
+RUN if [ -z "$RECIPES_TAG" ]; then echo "RECIPES_TAG argument is required"; exit 1; fi
+RUN if [ -z "$KERNEL_VER" ]; then echo "KERNEL_VER argument is required"; exit 1; fi
+
 # remove xbot2, install dependencies for building xenomai and the client
 RUN sudo apt update && \ 
     sudo apt remove -y xbot2 && \ 
